# Tests over the synthetic import fixtures in tests/testthat/fixtures/.
#
# The fixtures are generated by data-raw/make-import-fixtures.R and committed,
# so nothing here needs a spreadsheet writer.
#
# Every fixture describes the SAME cycle test. They differ only in language,
# units, and layout. So the strongest assertion available is that they all
# produce the same numbers, and that is what most of these tests check.

fixture <- function(name) test_path("fixtures", name)

skip_without_fixtures <- function() {
  skip_if(
    !file.exists(fixture("cosmed_en_synth.xlsx")),
    "Fixtures not generated; run data-raw/make-import-fixtures.R"
  )
}

# The reference values, taken from the plain English fixture.
expect_same_test <- function(data) {
  expect_equal(nrow(data@breaths), 72L)
  expect_equal(range(data@breaths$time_s), c(10, 720))
  expect_equal(round(stats::median(data@breaths$vo2_ml)), 1871)
  # NA is allowed: the French fixtures carry one row Omnia marked NONE.
  expect_setequal(stats::na.omit(unique(data@breaths$phase)),
                  c("rest", "warmup", "exercise"))
  expect_true(all(c("vo2_ml", "vco2_ml", "ve_l", "rer") %in% names(data@breaths)))
}


test_that("the English fixture imports", {
  skip_without_fixtures()
  data <- read_cpet(fixture("cosmed_en_synth.xlsx"), quiet = TRUE)

  expect_same_test(data)
  expect_identical(data@participant@name, "John Smith")
  expect_identical(data@participant@sex, "M")
  expect_equal(data@participant@age, 38)
  expect_equal(data@participant@weight_kg, 78)
})


# ---- the French file, which is what this work was for ----------------------

test_that("a French export imports completely", {
  skip_without_fixtures()
  data <- read_cpet(fixture("cosmed_fr_synth.xlsx"), quiet = TRUE)

  # Same test, same numbers, despite French headers, French phase labels,
  # French sex, VO2 in L/min, speed in m/s, and a French sheet name.
  expect_same_test(data)

  expect_identical(data@participant@name, "Marie Tremblay")
  expect_identical(data@participant@sex, "F")
  expect_equal(data@participant@age, 42)
  expect_equal(data@participant@height_cm, 165)
  expect_equal(data@participant@weight_kg, 58)

  # Dates written day first, the French convention.
  expect_identical(data@participant@date_of_birth, as.Date("1983-04-11"))
  expect_identical(data@metadata@test_date, as.Date("2025-06-15"))

  # Modality read from "Rampe velo 50W/palier", which contains no English word
  # that the old protocol-text matching would have found.
  expect_identical(data@metadata@modality, "cycling")
})

test_that("test details are found by label, not by row number", {
  skip_without_fixtures()
  # This is the detail that makes reading fixed cells untenable. A real Omnia
  # French export puts the protocol on row 13 and the ergometer on row 14,
  # where the English export has them on rows 8 and 7. Reading fixed cells
  # returns "Type de test" and "Effort Maximal" instead.
  data <- read_cpet(fixture("cosmed_fr_synth.xlsx"), quiet = TRUE)

  expect_identical(data@metadata@protocol, "Rampe vélo 50W/palier")
  expect_match(data@metadata@device, "Excalib", fixed = TRUE)

  # The environmental block is found by label too.
  expect_equal(data@metadata@pressure_mmhg, 754)
  expect_equal(data@metadata@temperature_c, 22)
  expect_equal(data@metadata@humidity_pct, 29)
})

test_that("a French file keeping English phase values still imports", {
  skip_without_fixtures()
  # Omnia translates the column headers and the header-block labels but leaves
  # the phase values in its own English vocabulary. The two are independent,
  # and the importer must not assume they travel together.
  data <- read_cpet(fixture("cosmed_fr_synth.xlsx"), quiet = TRUE)
  expect_true(all(c("rest", "warmup", "exercise") %in% data@breaths$phase))
})

test_that("a phase written NONE becomes NA without complaint", {
  skip_without_fixtures()
  # There is nothing for the user to fix about a row the cart did not assign,
  # so it must not be reported as an unrecognised label.
  expect_no_warning(
    data <- read_cpet(fixture("cosmed_fr_synth.xlsx"), quiet = TRUE)
  )
  expect_equal(sum(is.na(data@breaths$phase)), 1L)
})

test_that("a French file with translated phase values also imports", {
  skip_without_fixtures()
  data <- read_cpet(fixture("cosmed_fr_phases.xlsx"), quiet = TRUE)

  expect_setequal(unique(data@breaths$phase), c("rest", "warmup", "exercise"))
  expect_identical(data@participant@sex, "M")

  # "F Resp" and "Ventilation" are the French headers a real export uses.
  expect_true(all(c("bf", "ve_l") %in% names(data@breaths)))

  # Modality read from "Tapis roulant incremental" plus a Woodway treadmill.
  expect_identical(data@metadata@modality, "treadmill")
})

test_that("the French sheet name is found without being asked for", {
  skip_without_fixtures()
  # The old default of sheet = "Data" made readxl error outright on this file.
  expect_no_error(read_cpet(fixture("cosmed_fr_synth.xlsx"), quiet = TRUE))
  expect_no_error(read_cosmed(fixture("cosmed_fr_synth.xlsx"), quiet = TRUE))
})

test_that("VO2 declared in L/min is converted to mL/min", {
  skip_without_fixtures()
  data <- read_cpet(fixture("cosmed_fr_synth.xlsx"), quiet = TRUE)

  # The file holds values around 1.9; the analysis layer needs about 1900.
  # Without this the ventilatory equivalents come out a thousandfold wrong
  # while the threshold detectors still find a plausible-looking breakpoint.
  expect_gt(stats::median(data@breaths$vo2_ml), 1000)
  expect_lt(stats::median(data@breaths$vo2_ml), 3000)
})

test_that("VO2 in L/min is still caught when the file states no units", {
  skip_without_fixtures()
  no_units <- read_cpet(fixture("cosmed_fr_nounits.xlsx"), quiet = TRUE)
  declared <- read_cpet(fixture("cosmed_fr_synth.xlsx"), quiet = TRUE)

  # Same answer from the magnitude of the data alone.
  expect_equal(no_units@breaths$vo2_ml, declared@breaths$vo2_ml)
  expect_same_test(no_units)
})


# ---- awkward layouts and time formats --------------------------------------

test_that("time stored as an Excel day fraction is converted to seconds", {
  skip_without_fixtures()
  # This file's units row claims seconds while the values are day fractions,
  # which is exactly what a real COSMED export does. The magnitude has to be
  # allowed to overrule the stated unit, or the whole test lasts 0.008 s.
  data <- read_cpet(fixture("cosmed_en_daytime.xlsx"), quiet = TRUE)
  expect_same_test(data)
})

test_that("time written as hh:mm:ss is parsed", {
  skip_without_fixtures()
  # as.numeric("00:10:30") is NA, which used to empty the whole table and then
  # report a missing column rather than the real cause.
  data <- read_cpet(fixture("cosmed_en_clocktime.xlsx"), quiet = TRUE)
  expect_same_test(data)
})

test_that("a bare sheet with no header block imports", {
  skip_without_fixtures()
  # Header on row 1, data from row 2, first column, no units row and no
  # participant block. The old importer read fixed cells and could not.
  data <- read_cpet(fixture("cosmed_minimal.xlsx"), quiet = TRUE)
  expect_same_test(data)

  # With no header block there is nothing to read, so the defaults apply
  # rather than stray data values being mistaken for a participant.
  expect_identical(data@participant@name, "Unknown")
  expect_null(data@metadata@temperature_c)
})

test_that("two columns claiming one variable does not corrupt the data", {
  skip_without_fixtures()
  data <- read_cpet(fixture("cosmed_conflict.xlsx"), quiet = TRUE)
  expect_same_test(data)
  expect_equal(sum(names(data@breaths) == "ve_l"), 1L)
})


# ---- files that must be refused --------------------------------------------

test_that("a missing required column is refused, naming what was found", {
  skip_without_fixtures()
  expect_error(
    read_cpet(fixture("cosmed_missing.xlsx"), quiet = TRUE),
    class = "cardiometr_missing_required"
  )
  # The message has to name the file's own columns, not only the internal
  # ones, or the user has nothing to act on.
  expect_error(
    read_cpet(fixture("cosmed_missing.xlsx"), quiet = TRUE),
    "vco2_ml"
  )
})

test_that("a file with no recognisable header is refused", {
  skip_without_fixtures()
  expect_error(
    read_cpet(fixture("junk.xlsx"), quiet = TRUE),
    class = "cardiometr_header_not_found"
  )
})


# ---- user overrides --------------------------------------------------------

test_that("mapping lets a user name a column the format does not know", {
  skip_without_fixtures()
  # Pretend the alias table has never heard of "Puissance".
  data <- read_cpet(
    fixture("cosmed_fr_synth.xlsx"),
    mapping = c("Puissance" = "power_w"),
    quiet = TRUE
  )
  expect_true("power_w" %in% names(data@breaths))
  expect_equal(max(data@breaths$power_w), 250)
})

test_that("units lets a user overrule what the file claims", {
  skip_without_fixtures()
  # Declaring VO2 as mL/min when the file says L/min must skip the conversion.
  data <- read_cpet(
    fixture("cosmed_fr_synth.xlsx"),
    units = c(vo2_ml = "mL/min"),
    quiet = TRUE
  )
  expect_lt(stats::median(data@breaths$vo2_ml), 20)
})
